language: java
jdk: openjdk8

before_install:
  - ls -la
  - echo $GPG_PASSPHRASE | gpg --import travis.gpg
  - rm -f travis.gpg
  - cp settings.template.xml $HOME/.m2/settings.xml

script:
  - mvn -P hb3,travis clean install
  - mvn -P hb4,travis clean install
    
deploy:
  provider: script
  script: mvn -P hb3,travis deploy -DskipTests=true && mvn -P hb4,travis deploy -DskipTests=true
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^(deploy_.*|publish_.*)$